### ISSUE TITLE
Put a users on the Team page

### ISSUE THREAD

**Issue by jesseparent** [BradCassityDev/git-ticketing-system#102]
Display all users per team in a table cell separated by commas
Is the Sequelize Include to join the team and user tables

**Comment by jesseparent** [comment]
look at 
controllers/frontend/adminRoutes.js for the /team route and do a join using include
you will need to render the team-center handlebar page adding the list of users

**Comment by jrogerson20** [comment]
finished, did a PR. it seemed to push it from my computer in the Develop folder even though I did all the work in the feature branch.
