### ISSUE TITLE
Issue PUT API

### ISSUE THREAD

**Issue by jesseparent** [BradCassityDev/git-ticketing-system#14]
Update issue status in database
- Closed status sends status change to GitHub
- Closed status sends notifications to Clients who have a ticket related to issue

Update issue due date

Update assigned user
- Send assignment to GitHub
- Send email and text notifications to assigned user

**Comment by BradCassityDev** [comment]
Needing to send notifications. This was one of my 'aha' moments and hope to come up with a good with a good solution with Jesse soon.

**Comment by BradCassityDev** [comment]
Double check with Jesse before demo. How to handle updates? Modal?
