### ISSUE TITLE
Project CRUD

### ISSUE THREAD

**Issue by jesseparent** [BradCassityDev/git-ticketing-system#24]
Project creation will require a GitHub repository name and an initial Project_State
Project Get should return all projects or one project
Project Update will be able to edit name, GitHub repo name, and Project_State
Project cannot be deleted

**Comment by BradCassityDev** [comment]
Create basic routes to interact with project table. We’ll need to add more details to be returned later.

**Comment by BradCassityDev** [comment]
This should be completed for the time being. Will reopen if need be.
