### ISSUE TITLE
Admin permission required for certain routes

### ISSUE THREAD

**Issue by jesseparent** [BradCassityDev/git-ticketing-system#58]
Ticket editing
User Creation and editing
Team CRUD
Project CRUD

**Comment by heather-everton** [comment]
add withAuthAdmin and include the role id and import the session.

**Comment by heather-everton** [comment]
Ticket editing
router.put('/:id', withAuthAdmin, (req, res) 
router.delete('/:id', withAuthAdmin, (req, res)

User Creation/edit
router.post('/', withAuthAdmin, (req, res)
router.put('/:id', withAuthAdmin, (req, res)

Team CRUD
router.post('/', withAuthAdmin, (req, res)
router.get('/', withAuthAdmin, (req, res)
router.get('/:id' withAuthAdmin, (req, res)
router.put('/:id', withAuthAdmin, (req, res)
*no delete on teams

Project CRUD
router.get('/', withAuthAdmin, (req, res)
router.get('/:id', withAuthAdmin, (req, res)
router.post('/', withAuthAdmin, (req, res)
router.put('/:id', withAuthAdmin, (req, res)

**Comment by heather-everton** [comment]
Currently this is working using two separate auth files. There may be a cleaner way to do this. We can discuss at stand up if I should refactor.
